apiVersion: v1
kind: Service
metadata:
  name: version-api
  labels:
    app.kubernetes.io/name: version-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: version-api
---
apiVersion: v1
kind: Service
metadata:
  name: version-api-canary
  labels:
    app.kubernetes.io/name: version-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: version-api
